### PR TITLE
VIX-3332 Timeline Color is not getting initialized properly for user created fixture functions

### PR DESCRIPTION
**Pull request by johncbaur**
VIX-3332 Timeline Color is not getting initialized properly for user created fixture functions

### CODE REVIEW

**Review by jeffu231 — COMMENTED** [review]
Is there a reason why you did not just default it to white or some specific color other than transparent? Most everything else defaults to white. I may be missing something.

**Comment by johncbaur** [comment]
This color is not something the user can pick/edit.  So I am randomly
picking a color randomly from the known color enum.  The more I think about
it, I really probably should make sure the color has not already been used
on the fixture.  This color is used as a rainbow background on the timeline
for the fixture effect.  So the user might correlate well this fixture
effect has, pan (red), tilt (green), and prism (pink).

**Comment by johncbaur** [comment]
I am thinking I should add logic to make sure colors are not repeated and perhaps give preference to primary colors.  I can do that with this ticket or create a new one.

**Comment by jeffu231** [comment]
Go ahead an enhance the description on this ticket and just do it all together.

**Pull request closed without merging**
